name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "docs/**"
    - ".github/workflows/deploy-docs.yml"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    concurrency:
      group: docs
    steps:
    - uses: actions/checkout@v3
    # https://github.com/marketplace/actions/mdbook-action
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - name: Cache Rust Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
        key: docs-${{ runner.os }}
    - name: Install mdBook & mdBook-i18n
      run: ./scripts/install.sh
    - name: Build docs
      run: sed -i 's|var basePath = "/";|var basePath = "/holoinsight-docs/";|' ./docs/theme/index.hbs  && ./scripts/build.sh
    - name: Upload docs
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs/book/html
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
